Refactor Actions to use more caching and lint them
Use zizmor to lint the GitHub Actions workflows. Fix some of the issues
it brought up, like pinning third-party actions to commits instead of
version tags. Make use of caching of pip packages and Ensaio data
downloads to minimize traffic and build times. Combine all style checks
into a single job to avoid the overhead of setting up a virtual machine.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,13 +18,16 @@ on:
     types:
       - published
 
+permissions: {}
+
 # Use bash by default in all jobs
 defaults:
   run:
-    # Using "-l {0}" is necessary for conda environments to be activated
+    # The -l {0} is necessary for conda environments to be activated
     # But this breaks on MacOS if using actions/setup-python:
     # https://github.com/actions/setup-python/issues/132
-    shell: bash
+    # -e makes sure builds fail if any command fails
+    shell: bash -e -o pipefail -l {0}
 
 jobs:
 
@@ -32,24 +35,19 @@ jobs:
   # Run tests
   test:
     name: ${{ matrix.os }} python=${{ matrix.python }} dependencies=${{ matrix.dependencies }}
-    runs-on: ${{ matrix.os }}-latest
+    runs-on: ${{ matrix.os }}
     strategy:
       # Otherwise, the workflow would stop if a single job fails. We want to
       # run all of them to catch failures in different combinations.
       fail-fast: false
       matrix:
-        os:
-          - ubuntu
-          - macos
-          - windows
-        dependencies:
-          - oldest
-          - latest
+        os: [ubuntu-latest, macos-latest, windows-latest]
+        python: ["3.9", "3.12"]
         include:
-          - dependencies: oldest
-            python: "3.9"
-          - dependencies: latest
-            python: "3.12"
+          - python: "3.9"
+            dependencies: oldest
+          - python: "3.12"
+            dependencies: latest
     env:
       REQUIREMENTS: env/requirements-build.txt env/requirements-test.txt
       # Used to tag codecov submissions
@@ -129,6 +127,16 @@ jobs:
       - name: Install the package
         run: python -m pip install --no-deps dist/*.whl
 
+      - name: Get the version of ensaio
+        id: ensaio-version
+        run: echo "v=$(grep ensaio env/requirements-docs.txt)" >> $GITHUB_OUTPUT
+
+      - name: Setup caching of Ensaio datasets
+        uses: actions/cache@v4
+        with:
+          path: ${{ runner.temp }}/cache/ensaio
+          key: ensaio-data-${{ steps.ensaio-version.outputs.v }}
+
       - name: Run the tests
         run: make test
 
@@ -163,7 +171,7 @@ jobs:
         run: ls -l -R .
 
       - name: Upload coverage reports to Codecov
-        uses: codecov/codecov-action@v5
+        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
         with:
           # Upload all coverage report files
           files: ./coverage_*/coverage.xml
